FROM ubuntu:12.04

# docker build -t logbt-precise -f Dockerfile.ubuntu-precise .
# docker run --privileged logbt-precise

ENV WORKINGDIR /usr/local/src
WORKDIR ${WORKINGDIR}
COPY bin/logbt bin/logbt
COPY test test
RUN apt-get update -y && \
 apt-get install -y bash curl gdb git-core g++ --no-install-recommends && \
 git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm/ && \
 . ~/.nvm/nvm.sh && \
 nvm install 4

CMD ./bin/logbt --test && \
    . ~/.nvm/nvm.sh && \
    nvm use 4 && \
    ./test/unit.sh