FROM springmeyer/logbt:latest

# docker build -t logbt-springmeyer -f Dockerfile.springmeyer-logbt-readonly .
# docker run logbt-springmeyer

ENV WORKINGDIR /usr/local/src
WORKDIR ${WORKINGDIR}
COPY bin/logbt bin/logbt
COPY test test
RUN apt-get update -y && \
 apt-get install -y bash curl gdb git-core g++ ca-certificates --no-install-recommends

RUN curl -sSfL https://s3.amazonaws.com/mapbox/apps/install-node/v2.0.0/run -o run && \
  chmod +x ./run && \
  NV=4.4.3 NP=$(uname | tr A-Z a-z)-x64 OD=/usr/local ./run

RUN cat /proc/sys/kernel/core_pattern

CMD ./bin/logbt --test && \
    ./test/unit.sh