FROM ubuntu:12.04

# docker build -t logbt-precise-writable -f Dockerfile.ubuntu-precise-writable-proc .
# docker run --volume /proc:/writable-proc logbt-precise-writable

ENV WORKINGDIR /usr/local/src
WORKDIR ${WORKINGDIR}
COPY bin/logbt bin/logbt
COPY test test
RUN apt-get update -y && \
 apt-get install -y bash curl gdb git-core g++ --no-install-recommends && \
 git clone --depth 1 https://github.com/creationix/nvm.git ~/.nvm/ && \
 . ~/.nvm/nvm.sh && \
 nvm install 4

CMD echo $(./bin/logbt --target-pattern) > /writable-proc/sys/kernel/core_pattern && \
    mkdir -p $(dirname $(./bin/logbt --target-pattern)) && \
    ./bin/logbt --test && \
    . ~/.nvm/nvm.sh && \
    nvm use 4 && \
    ./test/unit.sh
